Add Pico CAN Bus board definition class.

diff --git a/.github/workflows/ci-arduino-build.yml b/.github/workflows/ci-arduino-build.yml
--- a/.github/workflows/ci-arduino-build.yml
+++ b/.github/workflows/ci-arduino-build.yml
@@ -57,14 +57,35 @@ jobs:
           arduino-cli lib install ACAN2515
           arduino-cli lib install Streaming
 
-      - name: Compile all examples for ${{ matrix.label }}
+      - name: Compile all examples for ${{ matrix.label }} for CANSHIELD
         run: |
           results=""
-          for dir in ./examples/*; do
+          # Compile all the generic examples for all platforms
+          for dir in ./examples/VLCB_[0-9a-z]*; do
             if [ -d "$dir" ] && ls "$dir"/*.ino >/dev/null 2>&1; then
               exname=$(basename "$dir")
               echo "Compiling $dir"
               if arduino-cli compile --fqbn ${{ matrix.board }} --library . "$dir"; then
+                results="$results  PASS  $exname"$'\n'
+              else
+                results="$results  FAIL  $exname"$'\n'
+              fi
+            fi
+          done
+          echo "=== Summary ==="
+          echo "$results"
+          if echo "$results" | grep -q "^  FAIL"; then
+            exit 1
+          fi
+
+      - name: Compile all RPi Pico examples for Duncan's Pico CAN Bus board with the MCP2515 controller enabled. 
+        run: |
+          results=""
+          for dir in ./examples/VLCB_Pico*; do
+            if [ -d "$dir" ] && ls "$dir"/*.ino >/dev/null 2>&1; then
+              exname=$(basename "$dir")
+              echo "Compiling $dir"
+              if arduino-cli compile --fqbn rp2040:rp2040:rpipico --library . "$dir"; then
                 results="$results  PASS  $exname"$'\n'
               else
                 results="$results  FAIL  $exname"$'\n'
